### ISSUE TITLE
Store time of registration for users

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/SS14.Auth#1]
We need to be able to flex on others with account creation times.

**Comment by ancientpower** [comment]
Suggest adding rounds played to this since it'd be clutter to make a separate issue.

**Comment by SweptWasTaken** [comment]
Suggest adding number of times a player has said "yiff"

**Comment by PJB3005** [comment]
Unless we want to work on a stat tracking system aswell that's for a different project.

**Comment by ancientpower** [comment]
I think rounds played should be grouped with date of registration before worrying about general stat tracking since those two are actually critical admin tools.

**Comment by PJB3005** [comment]
I want to remind you that this is a *global* database, for *all* game servers. Tracking registration date is trivial. Tracking stats such as rounds played is not (has to be per server/server group).

It would be best to track such things in the game server's databases right now and if we feel like it we can migrate the data to a "for every server" project later.

**Comment by ancientpower** [comment]
Okay yeah on second thought tracking stats on a cross-server basis is probably a bad idea for the reasons stated + they could easily be spoofed. My bad.

**Comment by PJB3005** [comment]
> they could easily be spoofed

Yep, don't want some random inflating their global round count with a modified server to seem like a "legit" account.
